# Generated by Django 4.2.1 on 2023-05-16 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lokikirja_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='lokikirja_app.logbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
