# Generated by Django 4.2.1 on 2023-05-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokikirja_app', '0005_remove_userprofile_age_remove_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='mirror',
            field=models.BooleanField(default=False),
        ),
    ]
