# Generated by Django 4.2.1 on 2023-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lokikirja_app', '0007_mirrorlogbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='message',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='message',
            field=models.TextField(max_length=10000),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
